# https://github.com/helm/chart-releaser-action#example-workflow
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git submodule update --init

      - name: Install Helm
        uses: azure/setup-helm@v3

      # https://github.com/murz-helm-charts/murz-helm-charts/blob/5098a941604390e5abfa545c3c4b4b152b2732d9/.github/workflows/release.yml#L23C7-L29C70
      # https://github.com/helm/chart-releaser-action/issues/74#issuecomment-778787114
      - name: Add dependencies
        run: |
          # for dir in charts/*; do (cd $dir && helm dependency update); done
          # This should work automatically? Issue https://github.com/helm/chart-releaser-action/issues/6

          helm repo add hashicorp https://helm.releases.hashicorp.com

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
